name: Build React on S3
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: PreBuild
        run: |
          curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -; sudo apt-get update

      - name: Checkout
        uses: actions/checkout@main

      - name: Install Dependencies
        run: yarn

      - name: Create .env.develop
        env:
          REACT_APP_API_ENDPOINT: ${{ secrets.REACT_APP_API_ENDPOINT }}
        run: echo REACT_APP_API_ENDPOINT=${REACT_APP_API_ENDPOINT} > .env.develop

      - name: Build
        run: yarn build:dev

      - name: Deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          DEPLOY_S3_URL: ${{ secrets.DEPLOY_S3_URL }}
        run: |
          aws s3 cp --recursive --region ap-northeast-1 build ${DEPLOY_S3_URL}
